In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2026-02-22 08:05:43.597517: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1968, 4293, 5228, 8204],
 [1968, 4293, 5228, 6447],
 [1968, 3266, 5228, 6888],
 [639, 9921, 571, 3716, 1621],
 [639, 9921, 571, 3716, 5436],
 [3720, 1968, 1491, 5228, 107],
 [7001, 9616, 4396, 3716]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1968 4293 5228 8204]
 [   0    0    0    0 1968 4293 5228 6447]
 [   0    0    0    0 1968 3266 5228 6888]
 [   0    0    0  639 9921  571 3716 1621]
 [   0    0    0  639 9921  571 3716 5436]
 [   0    0    0 3720 1968 1491 5228  107]
 [   0    0    0    0 7001 9616 4396 3716]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/home/dragon/.virtualenvs/nlp/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
I0000 00:00:1771747577.342264   23638 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3582 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[[-0.02312787, -0.01882362, -0.02935264,  0.0327157 ,
          0.01645917,  0.04988661, -0.01726954, -0.03587549,
         -0.0364243 , -0.02011876],
        [-0.02312787, -0.01882362, -0.02935264,  0.0327157 ,
          0.01645917,  0.04988661, -0.01726954, -0.03587549,
         -0.0364243 , -0.02011876],
        [-0.02312787, -0.01882362, -0.02935264,  0.0327157 ,
          0.01645917,  0.04988661, -0.01726954, -0.03587549,
         -0.0364243 , -0.02011876],
        [-0.02312787, -0.01882362, -0.02935264,  0.0327157 ,
          0.01645917,  0.04988661, -0.01726954, -0.03587549,
         -0.0364243 , -0.02011876],
        [-0.04191717,  0.04214168,  0.01176801,  0.03515638,
          0.01071364, -0.02366337,  0.02455508, -0.02933579,
         -0.00592134,  0.04277685],
        [ 0.02765551,  0.04576181, -0.01604686, -0.03367076,
         -0.03181165,  0.04689049,  0.02304263, -0.01193922,
         -0.00564352,  0.04899697],
        [-0.00911125, -0.03117797, -0.0241869 , -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 1968, 4293, 5228, 8204], dtype=int32)

In [22]:
import numpy as np

In [24]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step


array([[[-0.02312787, -0.01882362, -0.02935264,  0.0327157 ,
          0.01645917,  0.04988661, -0.01726954, -0.03587549,
         -0.0364243 , -0.02011876],
        [-0.02312787, -0.01882362, -0.02935264,  0.0327157 ,
          0.01645917,  0.04988661, -0.01726954, -0.03587549,
         -0.0364243 , -0.02011876],
        [-0.02312787, -0.01882362, -0.02935264,  0.0327157 ,
          0.01645917,  0.04988661, -0.01726954, -0.03587549,
         -0.0364243 , -0.02011876],
        [-0.02312787, -0.01882362, -0.02935264,  0.0327157 ,
          0.01645917,  0.04988661, -0.01726954, -0.03587549,
         -0.0364243 , -0.02011876],
        [-0.04191717,  0.04214168,  0.01176801,  0.03515638,
          0.01071364, -0.02366337,  0.02455508, -0.02933579,
         -0.00592134,  0.04277685],
        [ 0.02765551,  0.04576181, -0.01604686, -0.03367076,
         -0.03181165,  0.04689049,  0.02304263, -0.01193922,
         -0.00564352,  0.04899697],
        [-0.00911125, -0.03117797, -0.0241869 , -0.0